name: QE Automated Testing via Selenium WebDriver (Java)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: --privileged

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Set up Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose -v

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Start Selenium Grid
      run: docker-compose up -d

    - name: Install local JAR files into Maven repository
      run: |
        mvn install:install-file -Dfile=bin/Fillo-1.9.jar -DgroupId=Fillo -DartifactId=fillo -Dversion=1.22 -Dpackaging=jar
        mvn install:install-file -Dfile=bin/ACOE_SeleniumHybridFramework_Bootcamp.jar -DgroupId=Framework -DartifactId=framework -Dversion=1.0 -Dpackaging=jar

    - name: Make ChromeDriver executable
      run: chmod +x src/main/resources/webdriver/chromedriver.exe

    - name: Run Maven build and tests
      run: mvn clean install

    - name: Shutdown Docker Compose
      run: docker-compose down

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: src/test/resources/reports/consolidated/**
